[mission]
name           = "test"
pi             = "jgrelet"
organization   = "IRD"

[global]
debug          = false
echo           = true
log            = "geo-acq.log"

[acq]
file           = "geo-acq.sqlite"

[devices]

	[devices.gps]
	type           = "nmea"
	use            = true
	device         = "serial"
	sentence       = "GGA,RMC"

	[devices.echosounder]
	type           = "nmea"
	use            = false
	device         = "serial"
	sentence       = "DBT"

[serials]

	[serials.gps]
	port           = "/dev/ttyUSB0"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

	[serials.echosounder]
	port           = "/dev/ttyUSB1"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

[udp]

	[udp.gps]
	host           = ""
	port           = "10183"

	[udp.echosounder]
	host           = ""
	port           = "10184"
