[global]
mission        = "test"
author         = "jgrelet IRD nov 2017"
debug          = false
echo           = true
log            = "geo-acq.log"

[acq]
file           = "geo-acq.txt"

[devices]

	[devices.gps]
	type           = "nmea"
	use            = true
	device         = "serial"

	[devices.echosounder]
	type           = "nmea"
	use            = false
	device         = "serial"

[serials]

	[serials.gps]
	port           = "/dev/ttyUSB0"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

	[serials.echosounder]
	port           = "/dev/ttyUSB1"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

[udp]

	[udp.gps]
	host           = ""
	port           = "10183"

	[udp.echosounder]
	host           = ""
	port           = "10184"
