[global]
author         = "jgrelet IRD nov 2017"
debug          = false
echo           = true
log            = "nmea.log"

[acq]
file           = "nmea.txt"

[gps]
type           = "nmea"
use            = true
device 	       = "/dev/ttyUSB0"
baud           = 4800


[echosounder]
use            = false
type           = "nmea"
device 	       = "/dev/ttyUSB1"
baud           = 4800

