[global]
author         = "jgrelet IRD jan 2018"
debug          = false
echo           = true
log            = "geo-acq.log"

[acq]
file           = "geo-acq.txt"

[devices]

	[devices.gps]
	type           = "nmea"
	use            = true
	device         = "udp"

	[devices.echosounder]
	type           = "nmea"
	use            = false
	device         = "udp"

[serials]

	[serials.gps]
	port 	       = "COM20"
	baud           = 4800
	parity	       = "none"
	databit        = 8
	stopbit        = 1

	[serials.echosounder]
	port 	       = "COM16"
	baud           = 4800
	parity	       = "none"
	databit        = 8
	stopbit        = 1

[udp]

	[udp.gps]
	port           = "10183"

	[udp.echosounder]
	port           = "10184"



