[mission]
name           = "dev"
pi             = "J.Grelet"
organization   = "IRD"

[global]
debug          = false
echo           = true
log            = "geo-acq.log"

[backup]
raw            = true
processed      = true
raw_path       = "examples"
processed_path = "examples"

[devices]

	[devices.gps]
	type           = "nmea"
	mode           = "simulate"
	device         = "serial"
	sentence       = "GGA,RMC"

	[devices.echosounder]
	type           = "nmea"
	mode           = "simulate"
	device         = "serial"
	sentence       = "DBT"

[serials]

	[serials.gps]
	port 	       = "COM3"
	baud           = 4800
	parity	       = "none"
	databit        = 8
	stopbit        = 1

	[serials.echosounder]
	port 	       = "COM16"
	baud           = 4800
	parity	       = "none"
	databit        = 8
	stopbit        = 1

[udp]

	[udp.gps]
	host           = ""
	port           = "10183"

	[udp.echosounder]
	host           = ""
	port           = "10184"
