[mission]
name           = "udp-listener"
pi             = "the PI"
organization   = "theName"

[backup]
raw            = true
processed      = false

[export]
output         = "export-slowest.tsv"
mode           = "slowest_device"
mission        = "udp-listener"
session_id     = 0
interval       = ""
