[mission]
name           = "udp-listener"
pi             = "the PI"
organization   = "theName"

[backup]
raw            = true
processed      = false

[export]
output         = "export-fixed.tsv"
mode           = "fixed_interval"
mission        = "udp-listener"
session_id     = 0
interval       = "1s"
