[mission]
name           = "udp-listener"
pi             = "the PI"
organization   = "theName"

[global]
debug          = false
echo           = true
log            = "geo-acq-udp-listener.log"

[acq]
file           = "geo-acq-udp-listener.sqlite"

[devices]

	[devices.gps]
	type           = "nmea"
	use            = true
	device         = "udp"

	[devices.echosounder]
	type           = "nmea"
	use            = true
	device         = "udp"

[serials]

	[serials.gps]
	port           = "COM21"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

	[serials.echosounder]
	port           = "COM16"
	baud           = 4800
	parity         = "none"
	databit        = 8
	stopbit        = 1

[udp]

	[udp.gps]
	host           = ""
	port           = "10183"

	[udp.echosounder]
	host           = ""
	port           = "10184"
