// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function LoadConfig(arg1) {
  return window['go']['main']['App']['LoadConfig'](arg1);
}

export function RefreshSerialPorts() {
  return window['go']['main']['App']['RefreshSerialPorts']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SelectConfigFile() {
  return window['go']['main']['App']['SelectConfigFile']();
}

export function StartAcquisition() {
  return window['go']['main']['App']['StartAcquisition']();
}

export function StartDemo() {
  return window['go']['main']['App']['StartDemo']();
}

export function StopAcquisition() {
  return window['go']['main']['App']['StopAcquisition']();
}
