// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetState():Promise<main.AppState>;

export function LoadConfig(arg1:string):Promise<main.AppState>;

export function RefreshSerialPorts():Promise<Array<string>>;

export function SaveConfig(arg1:string):Promise<main.AppState>;

export function StartAcquisition():Promise<void>;

export function StartDemo():Promise<void>;

export function StopAcquisition():Promise<void>;
